name: Build and Upload Artifacts

on:
  push:
    branches: [ "*" ]
  pull_request_target:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build hexdiff for Linux
        run: |
          gcc -O2 -o hexdiff hexdiff.c

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: hexdiff-linux
          path: hexdiff

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build hexdiff for Windows
        run: |
          gcc -O2 -o hexdiff.exe hexdiff.c

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: hexdiff-windows
          path: hexdiff.exe
